#!/usr/bin/env fish

# ROOTSYS
if set -q ROOTSYS
	set -gx CONDA_BACKUP_ROOTSYS "$ROOTSYS"
end
set -gx ROOTSYS "$CONDA_PREFIX"

# ROOT_INCLUDE_PATH
if set -q ROOT_INCLUDE_PATH
	set -gx CONDA_BACKUP_ROOT_INCLUDE_PATH "$ROOT_INCLUDE_PATH"
end
set -gx ROOT_INCLUDE_PATH "$CONDA_PREFIX/include"

# ROOT_LIBRARY_PATH
if set -q ROOT_LIBRARY_PATH
	set -gx CONDA_BACKUP_ROOT_LIBRARY_PATH "$ROOT_LIBRARY_PATH"
end
set -gx ROOT_LIBRARY_PATH "$CONDA_PREFIX/lib"

# CLING_MODULEMAP_FILES
if set -q CLING_MODULEMAP_FILES
	set -gx CONDA_BACKUP_CLING_MODULEMAP_FILES "$CLING_MODULEMAP_FILES"
	set -e CLING_MODULEMAP_FILES
end
