#!/usr/bin/env fish

# ROOTSYS
if set -q CONDA_BACKUP_ROOTSYS
	set -gx ROOTSYS "$CONDA_BACKUP_ROOTSYS"
	set -e CONDA_BACKUP_ROOTSYS
else
	set -e ROOTSYS
end

# ROOT_INCLUDE_PATH
if set -q CONDA_BACKUP_ROOT_INCLUDE_PATH
	set -gx ROOT_INCLUDE_PATH "$CONDA_BACKUP_ROOT_INCLUDE_PATH"
	set -e CONDA_BACKUP_ROOT_INCLUDE_PATH
else
	set -e ROOT_INCLUDE_PATH
end

# ROOT_LIBRARY_PATH
if set -q CONDA_BACKUP_ROOT_LIBRARY_PATH
	set -gx ROOT_LIBRARY_PATH "$CONDA_BACKUP_ROOT_LIBRARY_PATH"
	set -e CONDA_BACKUP_ROOT_LIBRARY_PATH
else
	set -e ROOT_LIBRARY_PATH
end

# CLING_MODULEMAP_FILES
if set -q CONDA_BACKUP_CLING_MODULEMAP_FILES
	set -gx CLING_MODULEMAP_FILES "$CONDA_BACKUP_CLING_MODULEMAP_FILES"
	set -e CONDA_BACKUP_CLING_MODULEMAP_FILES
else
	set -e CLING_MODULEMAP_FILES
end
