{% set versions = {
    "6.32.02": "332c763d2d5eb8a759893453637f24b3900476f73a1a4c7a205f8f7b3104f449",
    "6.34.08": "1ee4ed1a5acc661def41a033a91e8775b2a8f3841cb9b8502988bb23d2bc5d7a"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "root")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

{% set gnu_versions = {
    "6.32.02": "<=14"
} %}

{% set clang_versions = {
    "6.32.02": "16.0.6",
    "6.34.08": "18.1.8"
} %}

{% set clang_patches = {
    "6.32.02": "63202",
    "6.34.08": "63402"
} %}

{% set clang_version = clang_versions.get(version) %}
{% set clang_patches_version = "root_"+(clang_patches.get(version)) %}

{% set builtin_pyroot = True %}
{% set builtin_clang = False %}

source:
  url: "https://github.com/root-project/root/archive/refs/tags/v{{ version|replace(".", "-") }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  patches:
    - patches/root-x.xx.xx_cling-runtime-sysroot.patch
    - patches/root-x.xx.xx-osx-remove-hardcoded-sysroot.patch  # [osx]
    - patches/0001-Hacks.patch
    - patches/0001-Patch-for-apple-silicon.patch
    - patches/0001-Set-LLVM_REQUIRES_EH-for-Cling.patch
    - patches/disable-hsimple.root  # [build_platform != target_platform]
    - patches/0001-force-one-modulemap-for-darwin.patch  # [osx]
    - patches/0001-Remove-check-for-SDK-version-in-CIFactory.patch  # [osx]
    - patches/0001-avoid-linking-TPython-against-libPython.patch  # [osx]
    - patches/0001-std_darwin.modulemap-Remove-headers-for-MacOSX15.0.s.patch  # [osx]
    - patches/0001-Hackily-fix-cross-compilation.patch
    - patches/0001-veccore-jobserver-issue.patch
{% if version < "6.34" %}
    - patches/0001-Reset-CMAKE-module-path-for-interpreter.patch
    - patches/0001-clad-jobserver-issue.patch
{% endif %}

build:
  ignore_prefix_files:
    - lib/*.pcm            # [not aarch64]
    - etc/allDict.cxx.pch  # [aarch64]
  ignore_run_exports_from:
    - clangdev
    - xorg-libx11
    - xorg-libxft
    - xorg-libxext
    - xorg-libxpm
    - xorg-libxrender
    - xorg-libxt
    - gsl
    - zlib
    - davix
    - cfitsio
    - tbb
    
  script_env:
    - clang_version={{ clang_version }}
    - clang_patches_version={{ clang_patches_version }}
    {% if builtin_pyroot %}- ROOT_CONDA_BUILTIN_PYROOT=1 {%- endif %}
    {% if builtin_clang %}- ROOT_CONDA_BUILTIN_CLANG=1 {%- endif %}
    {% if "ROOT_CONDA_BUILD_TYPE" in os.environ %}- ROOT_CONDA_BUILD_TYPE {%- endif %}

requirements:
  build:
    - {{ compiler('c') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ compiler('cxx') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ stdlib('c') }}

    - autoconf
    - cmake<=3.31
    - git
    - pkg-config
    - sed
    - make

    # Required for OpenGL support
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]

  host:
    - {{ compiler('c') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ compiler('cxx') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ stdlib('c') }}

    - libblas
    - libcblas
    - libstdcxx-ng
    - libcxx
    - binutils
    - openmp
{% if builtin_pyroot %}
    - python
    - numpy
{% endif %}
    - afterimage
    - lz4-c
    - xxhash
    - cfitsio
    - gdk-pixbuf # [win]
    - giflib
    - freetype
    - gtest
    - libxml2
    - ftgl
    - glew
    - gl2ps
    - glib
    - gsl
    - nlohmann_json
    - pcre2
    - fftw
    - zlib
    - zlib-ng
    - zstd
    - tbb
    - tbb-devel
    - vector-classes
    - vdt
    - libglu
    - xz
    - graphviz
    - pythia
    - xrootd
    - openssl
    - davix>=0.6.4
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-xorgproto # [linux]
{% if not builtin_clang %}
    - llvm {{ clang_version }}  # [not (osx and arm64)]
    - llvmdev {{ clang_version }}  # [not (osx and arm64)]
    - clangdev {{ clang_version }} {{ clang_patches_version }}*  # [not (osx and arm64)]
{% endif %}

  run:
{% if builtin_pyroot %}
    - python
{% endif %}
    - {{ compiler('c') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ compiler('cxx') }}{{ gnu_versions.get(version, "") }} # [linux]
    - {{ stdlib('c') }}

    - libstdcxx-ng
    - libcxx
    - xxhash
    - nlohmann_json
    - xz
    - libglu
    - graphviz
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxft  # [linux]
    - xorg-xorgproto # [linux]
    - vdt
    - tbb
    - tbb-devel
    - davix>=0.6.4


test:
  files:
    - test.cpp
  commands:
    - root -l -b -q -x
    - root -l -b -q -x test.cpp
    # When testing with -e, explicitly set the return code to zero
    - root -b -l -q -x -e '2+3; 0'
    - root -b -l -q -x -e 'gSystem->LoadAllLibraries(); 0'
    # Test if OpenGL is working
    - root -b -l -q -x -e 'gStyle->SetCanvasPreferGL(kTRUE); c = new TCanvas(); if (!c->UseGL()) { throw std::runtime_error("OpenGL does not appear to be working"); }'
    # This tutorial uses davix to access a ROOT file over HTTP
    - root -b -l -q -x "${PREFIX}/tutorials/tree/run_h1analysis.C"


about:
  home: https://root.cern/
  license: LGPL-2.1-only
  summary: "ROOT: analyzing petabytes of data, scientifically."
  description: |
      ROOT is a modular scientific software toolkit. It provides all the functionalities needed to deal with big data
      processing, statistical analysis, visualisation and storage. It is mainly written in C++ but integrated with other
      languages such as Python and R.

extra:
  recipe-maintainers:
    - meiyasan
